name: Auto Content Generator

on:
  schedule:
    
cron: "0 /12 * *" # toutes les 12h
workflow_dispatch: # permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
- name: Checkout repo
      uses: actions/checkout@v3

      
- name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

      
- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

      
- name: Generate content with AI
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python - <<EOF
        import openai, os, datetime
        openai.api_key = os.environ["OPENAI_API_KEY"]

          topic = "Idée de business en ligne"
          today = datetime.date.today().isoformat()

          response = openai.Completion.create(
              engine="text-davinci-003",
              prompt=f"Génère un article de blog sur : {topic}.",
              maxtokens=500
          )

          content = response.choices[0].text.strip()

          with open("docs/article" + today + ".md", "w") as f:
              f.write("# Article généré automatiquement\n\n")
              f.write(content)
          EOF

      
- name: Commit new content
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add docs/
        git commit -m "Ajout auto d’un nouvel article"
        git push
﻿
